
---
- name: LAMP
  hosts: all

  tasks:
    - name: Installing Apache
      yum: 
        name: httpd
        state: installed

    - name: Enabling httpd service and start the service
      service: 
        name: httpd
        enabled: yes
        state: started
        
    - name: Add mariadb repository
      yum_repository:
        name: mariadb
        description: mariadb
        file: external_repos
        baseurl: http://yum.mariadb.org/10.5/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes        
    
    - name: Install MYSQL DB Community edition
      yum:
        name: 
          - mariadb-server
          - mariadb 
        state: latest

    - name: Start the MYSQL service
      service:
        name: mysqld
        enabled: yes
        state: started

    - name: Installing PHP
      yum:
        name: 
          - php 
          - php-mysql 
        state: latest
        
    - name: Reload service httpd
      ansible.builtin.systemd:
        name: httpd
        state: reloaded        

    - name: Download file and force basic auth
      get_url:
        url: https://raw.githubusercontent.com/jxadro/ansible/master/index.php
        dest: /var/www/html/index.php   

