
---
- name: LAMP
  hosts: all

  tasks:
    - name: Installing Apache
      yum: 
        name: httpd
        state: installed

    - name: Enabling httpd service and start the service
      service: 
        name: httpd
        enabled: yes
        state: started
        
    - name: Add mariadb repository
      yum_repository:
        name: MariaDB-10.3.14
        description: MariaDB repo
        file: external_repos
        baseurl: http://yum.mariadb.org/10.3.14/centos7-amd64
        gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
        gpgcheck: yes        
    
    - name: Install MYSQL DB Community edition
      yum:
        name: 
          - maraidb-server
          - maraidb 
        state: latest

    - name: Start the MYSQL service
      service:
        name: mysqld
        enabled: yes
        state: started


    - name: Installing PHP
      yum:
        name: 
          - php 
          - php-mysql 
        state: latest

#    - name: Copying your php file in the /var/www/html
#      copy:
#        src: /root/ansibleplaybook/index.php
#        dest: /var/www/html/index.php

