- name: LAMP Stack
  hosts: all

  tasks:
    - name: Installing Apache
      yum: 
        name: httpd
        state: installed

    - name: Enabling httpd service and start the service
      service: 
        name: httpd
        enabled: yes
        state: started

    - name: Download sample html
      get_url:
        url: https://raw.githubusercontent.com/jxadro/ansible/master/helloworld.html
        dest: /var/www/html/helloworld.html
    
